### ISSUE TITLE
Login issues and page crash 

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#105] opened 2017-12-05 11:25 UTC
When use is not logged in homepage, search, event_upload crashes with stack trace 
[TypeError at homepage.pdf](https://github.com/UCSD-CSE-210/UCSDEventHub/files/1530944/TypeError.at.homepage.pdf)

Registration works but login crashes on giving correct credentials (tested for organizer) Stack trace as follows
[TypeError at _login_.pdf](https://github.com/UCSD-CSE-210/UCSDEventHub/files/1530949/TypeError.at._login_.pdf)

**Comment by nikhilym** [comment] 2017-12-05 17:33
>> When user is not logged in homepage, search, event_upload crashes with stack trace
TypeError at homepage.pdf

@kdhiman0309 , Not able to reproduce this error. Did you try it on an incognito and sure that there is no user that is already signed in? You shouldn't be able to even navigate to the page event_upload if user is not logged in.

**Comment by nikhilym** [comment] 2017-12-05 17:36
>> Registration works but login crashes on giving correct credentials (tested for organizer) Stack trace as >> follows TypeError at login.pdf

@kdhiman0309 , even this is working fine for me. I could register a new organization and login using the org credentials. Can you try it on new browser without cache, and on latest code and update the issue? To make sure you don't have any user logged in, you should have register and sign in links on nav bar and not the user dropdown.

**Comment by nikhilym** [comment] 2017-12-06 07:08
Tested to be working fine. Issue was with Django version. Closing it since @kdhiman0309 confirmed it to be working as expected.

**Closed by nikhilym** 2017-12-06 07:08 UTC
Labels: bug, need-more-information
